// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package page

import "strconv"

type Data byte

const (
	DataNONE Data = 0
	DataRef  Data = 1
	DataReal Data = 2
)

var EnumNamesData = map[Data]string{
	DataNONE: "NONE",
	DataRef:  "Ref",
	DataReal: "Real",
}

var EnumValuesData = map[string]Data{
	"NONE": DataNONE,
	"Ref":  DataRef,
	"Real": DataReal,
}

func (v Data) String() string {
	if s, ok := EnumNamesData[v]; ok {
		return s
	}
	return "Data(" + strconv.FormatInt(int64(v), 10) + ")"
}
